apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: mysqlpassword1234
    image: mysql:5.6.36
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-disk
  volumes:
  - name: mysql-disk
    persistentVolumeClaim:
      claimName: volume-db-02
